// src/data.js
export const indianStates = [
  // Previous 20 States...
  {
    name: "Telangana",
    description: "Known for its rich history, monumental mosques and temples, and as a major IT hub.",
    language: "Telugu",
    headerImage: "/images/charminar-header.png",
    famousFood: [{ name: "Hyderabadi Biryani", image: "/images/biryani.png" }, { name: "Haleem", image: "/images/haleem.png" }],
    danceForm: { name: "Perini Sivatandavam", image: "/images/perini-dance.gif" },
    outfits: "Men traditionally wear the Pancha, while women adorn themselves in vibrant Pochampally sarees.",
    outfitImage: "/images/telangana-outfit.png",
    touristSpots: [{ name: "Charminar", image: "/images/charminar.png" }, { name: "Golconda Fort", image: "/images/golconda.png" }],
  },
  {
    name: "Andhra Pradesh",
    description: "Famous for its temples, such as Tirupati, and its spicy Andhra cuisine.",
    language: "Telugu",
    headerImage: "/images/tirupati-header.png",
    famousFood: [{ name: "Pulihora", image: "/images/pulihora.png" }, { name: "Gutti Vankaya Kura", image: "/images/gutti-vankaya.png" }],
    danceForm: { name: "Kuchipudi", image: "/images/kuchipudi-dance.gif" },
    outfits: "Dharmavaram sarees are famous for women, while men wear the Dhoti and Kurta.",
    outfitImage: "/images/andhra-outfit.png",
    touristSpots: [{ name: "Tirumala Temple", image: "/images/tirumala.png" }, { name: "Borra Caves", image: "/images/borra-caves.png" }],
  },
  {
    name: "Karnataka",
    description: "A land of ancient palaces, lush national parks, and the silicon valley of India, Bengaluru.",
    language: "Kannada",
    headerImage: "/images/mysore-header.png",
    famousFood: [{ name: "Bisi Bele Bath", image: "/images/bisi-bele-bath.png" }, { name: "Mysore Pak", image: "/images/mysore-pak.png" }],
    danceForm: { name: "Yakshagana", image: "/images/yakshagana-dance.gif" },
    outfits: "The Ilkal saree is a traditional attire for women, known for its unique weaving.",
    outfitImage: "/images/karnataka-outfit.png",
    touristSpots: [{ name: "Mysore Palace", image: "/images/mysore-palace.png" }, { name: "Hampi", image: "/images/hampi.png" }],
  },
  {
    name: "Kerala",
    description: "God's Own Country, renowned for its tranquil backwaters, coconut-lined beaches, and rich traditions.",
    language: "Malayalam",
    headerImage: "/images/backwaters-header.png",
    famousFood: [{ name: "Sadya", image: "/images/sadya.png" }, { name: "Appam with Stew", image: "/images/appam.png" }],
    danceForm: { name: "Kathakali", image: "/images/kathakali-dance.gif" },
    outfits: "The traditional attire is the Mundu for men and the elegant Kasavu saree for women.",
    outfitImage: "/images/kerala-outfit.png",
    touristSpots: [{ name: "Alleppey Backwaters", image: "/images/backwaters.png" }, { name: "Munnar", image: "/images/munnar.png" }],
  },
  {
    name: "Tamil Nadu",
    description: "A state of towering temples, classical dance, and beautiful hill stations.",
    language: "Tamil",
    headerImage: "/images/meenakshi-header.png",
    famousFood: [{ name: "Pongal", image: "/images/pongal.png" }, { name: "Chettinad Chicken", image: "/images/chettinad.png" }],
    danceForm: { name: "Bharatanatyam", image: "/images/bharatanatyam-dance.gif" },
    outfits: "The Kanchipuram silk saree is a world-renowned attire for women.",
    outfitImage: "/images/tamilnadu-outfit.png",
    touristSpots: [{ name: "Meenakshi Temple", image: "/images/meenakshi-temple.png" }, { name: "Ooty", image: "/images/ooty.png" }],
  },
  {
    name: "Maharashtra",
    description: "Home to the bustling metropolis of Mumbai, ancient caves, and historic forts.",
    language: "Marathi",
    headerImage: "/images/gateway-header.png",
    famousFood: [{ name: "Vada Pav", image: "/images/vada-pav.png" }, { name: "Misal Pav", image: "/images/misal-pav.png" }],
    danceForm: { name: "Lavani", image: "/images/lavani-dance.gif" },
    outfits: "Women traditionally wear the nine-yard Nauvari saree, while men wear a Dhoti and Pheta.",
    outfitImage: "/images/maharashtra-outfit.png",
    touristSpots: [{ name: "Gateway of India", image: "/images/gateway-header.png" }, { name: "Ajanta & Ellora Caves", image: "/images/ajanta-caves.png" }],
  },
  {
    name: "Punjab",
    description: "The land of five rivers, known for its vibrant Bhangra music, rich cuisine, and the Golden Temple.",
    language: "Punjabi",
    headerImage: "/images/golden-temple-header.png",
    famousFood: [{ name: "Makki di Roti & Sarson da Saag", image: "/images/makki-di-roti.png" }, { name: "Chole Bhature", image: "/images/chole-bhature.png" }],
    danceForm: { name: "Bhangra", image: "/images/bhangra-dance.gif" },
    outfits: "The traditional dress for women is the Salwar Kameez with a Phulkari dupatta, and for men, a Kurta and Tamba.",
    outfitImage: "/images/punjab-outfit.png",
    touristSpots: [{ name: "Golden Temple", image: "/images/golden-temple-header.png" }, { name: "Jallianwala Bagh", image: "/images/jallianwala-bagh.png" }],
  },
  {
    name: "Odisha",
    description: "A coastal state famous for its ancient temples, classical Odissi dance, and beautiful beaches.",
    language: "Odia",
    headerImage: "/images/konark-header.png",
    famousFood: [{ name: "Pakhala Bhata", image: "/images/pakhala-bhata.png" }, { name: "Chhena Poda", image: "/images/chenna-poda.png" }],
    danceForm: { name: "Odissi", image: "/images/odissi-dance.gif" },
    outfits: "The Sambalpuri saree is a handloom masterpiece and a traditional attire for women.",
    outfitImage: "/images/odisha-outfit.png",
    touristSpots: [{ name: "Konark Sun Temple", image: "/images/konark-header.png" }, { name: "Jagannath Puri Temple", image: "/images/jagannath-temple.png" }],
  },
  {
    name: "Assam",
    description: "Nestled in the northeast, famous for its lush tea gardens, the mighty Brahmaputra river, and unique wildlife.",
    language: "Assamese",
    headerImage: "/images/assam-tea-header.png",
    famousFood: [{ name: "Masor Tenga", image: "/images/masor-tenga.png" }, { name: "Khaar", image: "/images/khaar.png" }],
    danceForm: { name: "Bihu", image: "/images/bihu-dance.gif" },
    outfits: "The Mekhela Sador is the elegant and traditional attire for Assamese women.",
    outfitImage: "/images/assam-outfit.png",
    touristSpots: [{ name: "Kaziranga National Park", image: "/images/kaziranga-park.png" }, { name: "Kamakhya Temple", image: "/images/kamakhya-temple.png" }],
  },
  {
    name: "Gujarat",
    description: "Known for its vibrant Navratri festival, the legacy of Mahatma Gandhi, and the stunning Rann of Kutch.",
    language: "Gujarati",
    headerImage: "/images/rann-of-kutch-header.png",
    famousFood: [{ name: "Dhokla", image: "/images/dhokla.png" }, { name: "Thepla", image: "/images/thepla.png" }],
    danceForm: { name: "Garba", image: "/images/garba-dance.gif" },
    outfits: "The Chaniya Choli is the colorful and traditional attire for women, especially during festivals.",
    outfitImage: "/images/gujarat-outfit.png",
    touristSpots: [{ name: "Statue of Unity", image: "/images/statue-of-unity.png" }, { name: "Great Rann of Kutch", image: "/images/rann-of-kutch-header.png" }],
  },
  {
    name: "Rajasthan",
    description: "The 'Land of Kings', famous for its majestic forts, vibrant culture, and the great Thar Desert.",
    language: "Rajasthani",
    headerImage: "/images/hawa-mahal-header.png",
    famousFood: [{ name: "Dal Baati Churma", image: "/images/dal-baati-churma.png" }, { name: "Gatte ki Sabzi", image: "/images/gatte-ki-sabzi.png" }],
    danceForm: { name: "Ghoomar", image: "/images/ghoomar-dance.gif" },
    outfits: "Women wear the Ghagra Choli, and men wear the Dhoti and Angarkha with a colorful Pagri (turban).",
    outfitImage: "/images/rajasthan-outfit.png",
    touristSpots: [{ name: "Hawa Mahal", image: "/images/hawa-mahal-header.png" }, { name: "Jaisalmer Fort", image: "/images/jaisalmer-fort.png" }],
  },
  {
    name: "Uttar Pradesh",
    description: "The heartland of India, home to the iconic Taj Mahal, ancient cities, and the sacred Ganga river.",
    language: "Hindi",
    headerImage: "/images/taj-mahal-header.png",
    famousFood: [{ name: "Tunday Kababi", image: "/images/tunday-kababi.png" }, { name: "Petha", image: "/images/petha.png" }],
    danceForm: { name: "Kathak", image: "/images/kathak-dance.gif" },
    outfits: "A variety of clothing is worn, with the Saree for women and Kurta-Pajama for men being popular.",
    outfitImage: "/images/uttar-pradesh-outfit.png",
    touristSpots: [{ name: "Taj Mahal", image: "/images/taj-mahal-header.png" }, { name: "Varanasi Ghats", image: "/images/varanasi-ghats.png" }],
  },
  {
    name: "Himachal Pradesh",
    description: "A paradise for nature lovers and adventurers, nestled in the Himalayas with stunning mountain landscapes.",
    language: "Hindi",
    headerImage: "/images/shimla-header.png",
    famousFood: [{ name: "Dham", image: "/images/dham.png" }, { name: "Madra", image: "/images/madra.png" }],
    danceForm: { name: "Nati", image: "/images/nati-dance.gif" },
    outfits: "Traditional attire includes the vibrant Kullu shawls, caps (Topi), and woolen clothing.",
    outfitImage: "/images/himachal-outfit.png",
    touristSpots: [{ name: "Shimla", image: "/images/shimla-header.png" }, { name: "Manali", image: "/images/manali.png" }],
  },
  {
    name: "Uttarakhand",
    description: "Known as 'Devbhumi' or the 'Land of the Gods', featuring holy rivers, forests, and the majestic Himalayas.",
    language: "Hindi",
    headerImage: "/images/rishikesh-header.png",
    famousFood: [{ name: "Aloo ke Gutke", image: "/images/aloo-ke-gutke.png" }, { name: "Kafuli", image: "/images/kafuli.png" }],
    danceForm: { name: "Chholiya", image: "/images/chholiya-dance.gif" },
    outfits: "Women wear a Ghagra with a Kameez and the traditional Pichora, a decorative veil.",
    outfitImage: "/images/uttarakhand-outfit.png",
    touristSpots: [{ name: "Rishikesh", image: "/images/rishikesh-header.png" }, { name: "Jim Corbett National Park", image: "/images/jim-corbett-park.png" }],
  },
  {
    name: "Haryana",
    description: "A state with a rich historical and archaeological past, known for its folklore and robust agricultural economy.",
    language: "Haryanvi, Hindi",
    headerImage: "/images/kurukshetra-header.png",
    famousFood: [{ name: "Bajre Ki Khichdi", image: "/images/bajre-ki-khichdi.png" }, { name: "Singri ki Sabzi", image: "/images/singri-ki-sabzi.png" }],
    danceForm: { name: "Saang", image: "/images/saang-dance.gif" },
    outfits: "The traditional dress for women is the Daman, Kurti and Chunder, and for men, a Dhoti-Kurta.",
    outfitImage: "/images/haryana-outfit.png",
    touristSpots: [{ name: "Kurukshetra", image: "/images/kurukshetra-header.png" }, { name: "Sultanpur Bird Sanctuary", image: "/images/sultanpur-bird-sanctuary.png" }],
  },
  {
    name: "West Bengal",
    description: "The cultural capital of India, known for its literature, colonial architecture, and vibrant festivals.",
    language: "Bengali",
    headerImage: "/images/howrah-bridge-header.png",
    famousFood: [{ name: "Rosogolla", image: "/images/rosogolla.png" }, { name: "Macher Jhol", image: "/images/macher-jhol.png" }],
    danceForm: { name: "Chhau Dance", image: "/images/chhau-dance.gif" },
    outfits: "The Tant saree for women and the Panjabi and Dhoti for men are iconic traditional attire.",
    outfitImage: "/images/bengal-outfit.png",
    touristSpots: [{ name: "Victoria Memorial", image: "/images/victoria-memorial.png" }, { name: "Sundarbans", image: "/images/sundarbans.png" }],
  },
  {
    name: "Bihar",
    description: "A land of ancient empires and spiritual enlightenment, home to the origins of Buddhism and Jainism.",
    language: "Hindi, Maithili",
    headerImage: "/images/mahabodhi-header.png",
    famousFood: [{ name: "Litti Chokha", image: "/images/litti-chokha.png" }, { name: "Sattu Paratha", image: "/images/sattu-paratha.png" }],
    danceForm: { name: "Bidesia Dance", image: "/images/bidesia-dance.gif" },
    outfits: "Traditional attire includes the Saree for women and the Dhoti-Kurta for men.",
    outfitImage: "/images/bihar-outfit.png",
    touristSpots: [{ name: "Mahabodhi Temple", image: "/images/mahabodhi-header.png" }, { name: "Nalanda University Ruins", image: "/images/nalanda-ruins.png" }],
  },
  {
    name: "Jharkhand",
    description: "Known as 'The Land of Forests', rich in minerals, tribal culture, and cascading waterfalls.",
    language: "Hindi, Santali",
    headerImage: "/images/dassam-falls-header.png",
    famousFood: [{ name: "Dhuska", image: "/images/dhuska.png" }, { name: "Rugra", image: "/images/rugra.png" }],
    danceForm: { name: "Paika Dance", image: "/images/paika-dance.gif" },
    outfits: "The traditional tribal attire for women is the Panchi and Parhan.",
    outfitImage: "/images/jharkhand-outfit.png",
    touristSpots: [{ name: "Dassam Falls", image: "/images/dassam-falls-header.png" }, { name: "Betla National Park", image: "/images/betla-national-park.png" }],
  },
  {
    name: "Madhya Pradesh",
    description: "The 'Heart of India', boasting rich history, magnificent wildlife, and ancient temple architecture.",
    language: "Hindi",
    headerImage: "/images/khajuraho-header.png",
    famousFood: [{ name: "Poha Jalebi", image: "/images/poha-jalebi.png" }, { name: "Bhutte ka Kees", image: "/images/bhutte-ka-kees.png" }],
    danceForm: { name: "Matki Dance", image: "/images/matki-dance.gif" },
    outfits: "Lehenga and Choli are popular traditional dresses, along with the beautiful Bandhani sarees.",
    outfitImage: "/images/madhya-pradesh-outfit.png",
    touristSpots: [{ name: "Khajuraho Temples", image: "/images/khajuraho-header.png" }, { name: "Sanchi Stupa", image: "/images/sanchi-stupa.png" }],
  },
  {
    name: "Chhattisgarh",
    description: "A heavily forested state known for its temples, waterfalls, and unique tribal arts and crafts.",
    language: "Chhattisgarhi, Hindi",
    headerImage: "/images/chitrakote-falls-header.png",
    famousFood: [{ name: "Faraa", image: "/images/faraa.png" }, { name: "Chila", image: "/images/chila.png" }],
    danceForm: { name: "Panthi Dance", image: "/images/panthi-dance.gif" },
    outfits: "The traditional attire for women is the Lugda, a type of saree, paired with a Polkha blouse.",
    outfitImage: "/images/chhattisgarh-outfit.png",
    touristSpots: [{ name: "Chitrakote Falls", image: "/images/chitrakote-falls-header.png" }, { name: "Tirathgarh Falls", image: "/images/tirathgarh-falls.png" }],
  },

  // NEW: Final Batch (Goa & Northeast)
  {
    name: "Goa",
    description: "India's sunshine state, famous for its golden beaches, vibrant nightlife, and Portuguese heritage.",
    language: "Konkani",
    headerImage: "/images/palolem-beach-header.png",
    famousFood: [{ name: "Goan Fish Curry", image: "/images/goan-fish-curry.png" }, { name: "Vindaloo", image: "/images/vindaloo.png" }],
    danceForm: { name: "Deknni Dance", image: "/images/deknni-dance.gif" },
    outfits: "The traditional Pano Bhaju is a nine-yard saree worn by women, reflecting a blend of cultures.",
    outfitImage: "/images/goa-outfit.png",
    touristSpots: [{ name: "Dudhsagar Falls", image: "/images/dudhsagar-falls.png" }, { name: "Fort Aguada", image: "/images/fort-aguada.png" }],
  },
  {
    name: "Sikkim",
    description: "A Himalayan wonderland, known for its pristine landscapes, Buddhist monasteries, and stunning mountain views.",
    language: "Nepali, Bhutia, Lepcha",
    headerImage: "/images/kangchenjunga-header.png",
    famousFood: [{ name: "Momos", image: "/images/momos.png" }, { name: "Thukpa", image: "/images/thukpa.png" }],
    danceForm: { name: "Mask Dance", image: "/images/mask-dance.gif" },
    outfits: "The traditional dress is the Bakhu (or Kho), a wrap-around garment worn by both men and women.",
    outfitImage: "/images/sikkim-outfit.png",
    touristSpots: [{ name: "Tsomgo Lake", image: "/images/tsomgo-lake.png" }, { name: "Rumtek Monastery", image: "/images/rumtek-monastery.png" }],
  },
  {
    name: "Arunachal Pradesh",
    description: "The 'Land of the Dawn-Lit Mountains', a remote paradise with diverse tribal cultures and stunning beauty.",
    language: "Multiple tribal languages",
    headerImage: "/images/tawang-header.png",
    famousFood: [{ name: "Pika Pila", image: "/images/pika-pila.png" }, { name: "Bamboo Shoot Fry", image: "/images/bamboo-shoot-fry.png" }],
    danceForm: { name: "Aji Lhamu Dance", image: "/images/aji-lhamu-dance.gif" },
    outfits: "Each tribe has its unique attire, often featuring colorful woven fabrics and intricate beadwork.",
    outfitImage: "/images/arunachal-outfit.png",
    touristSpots: [{ name: "Tawang Monastery", image: "/images/tawang-header.png" }, { name: "Ziro Valley", image: "/images/ziro-valley.png" }],
  },
  {
    name: "Manipur",
    description: "The 'Jewel of India', home to the floating Loktak Lake and the graceful Manipuri classical dance.",
    language: "Meitei (Manipuri)",
    headerImage: "/images/loktak-lake-header.png",
    famousFood: [{ name: "Eromba", image: "/images/eromba.png" }, { name: "Chamthong (Kangshoi)", image: "/images/chamthong.png" }],
    danceForm: { name: "Manipuri Ras Leela", image: "/images/ras-leela-dance.gif" },
    outfits: "The traditional dress for women is the elegant Phanek, paired with an Innaphi (shawl).",
    outfitImage: "/images/manipur-outfit.png",
    touristSpots: [{ name: "Loktak Lake", image: "/images/loktak-lake-header.png" }, { name: "Kangla Fort", image: "/images/kangla-fort.png" }],
  },
  {
    name: "Meghalaya",
    description: "The 'Abode of Clouds', famous for its living root bridges, cascading waterfalls, and lush green hills.",
    language: "Khasi, Garo, English",
    headerImage: "/images/living-root-bridge-header.png",
    famousFood: [{ name: "Jadoh", image: "/images/jadoh.png" }, { name: "Doh-Khlieh", image: "/images/doh-khlieh.png" }],
    danceForm: { name: "Nongkrem Dance", image: "/images/nongkrem-dance.gif" },
    outfits: "The traditional Khasi dress for women is the Jainsen, a beautiful unstitched garment.",
    outfitImage: "/images/meghalaya-outfit.png",
    touristSpots: [{ name: "Living Root Bridges", image: "/images/living-root-bridge-header.png" }, { name: "Cherrapunji", image: "/images/cherrapunji.png" }],
  },
  {
    name: "Mizoram",
    description: "A land of rolling hills and vibrant tribal culture, famous for the Cheraw (bamboo) dance.",
    language: "Mizo",
    headerImage: "/images/phawngpui-header.png",
    famousFood: [{ name: "Bai", image: "/images/bai.png" }, { name: "Vawksa Rep (Smoked Pork)", image: "/images/vawksa-rep.png" }],
    danceForm: { name: "Cheraw (Bamboo Dance)", image: "/images/cheraw-dance.gif" },
    outfits: "The traditional attire for women is the Puan, a beautifully woven cloth in intricate designs.",
    outfitImage: "/images/mizoram-outfit.png",
    touristSpots: [{ name: "Phawngpui Blue Mountain", image: "/images/phawngpui-header.png" }, { name: "Reiek Tlang", image: "/images/reiek-tlang.png" }],
  },
  {
    name: "Nagaland",
    description: "The 'Land of Festivals', known for its fierce warrior tribes, unique cuisine, and the Hornbill Festival.",
    language: "Multiple tribal languages, English",
    headerImage: "/images/dzukou-valley-header.png",
    famousFood: [{ name: "Smoked Pork with Axone", image: "/images/smoked-pork-axone.png" }, { name: "Galho", image: "/images/galho.png" }],
    danceForm: { name: "Naga Warrior Dance", image: "/images/warrior-dance.gif" },
    outfits: "Each tribe is identified by its unique, colorful shawls and traditional warrior costumes.",
    outfitImage: "/images/nagaland-outfit.png",
    touristSpots: [{ name: "Dzukou Valley", image: "/images/dzukou-valley-header.png" }, { name: "Kisama Heritage Village", image: "/images/kisama-village.png" }],
  },
  {
    name: "Tripura",
    description: "A hilly state with a rich history of royal palaces, rock carvings, and exquisite bamboo handicrafts.",
    language: "Bengali, Kokborok",
    headerImage: "/images/ujjayanta-palace-header.png",
    famousFood: [{ name: "Mui Borok", image: "/images/mui-borok.png" }, { name: "Kosoi Bwtwi", image: "/images/kosoi-bwtwi.png" }],
    danceForm: { name: "Hojagiri Dance", image: "/images/hojagiri-dance.gif" },
    outfits: "The traditional attire includes the Rignai (a wrap-around skirt) and Risa (a chest cloth) for women.",
    outfitImage: "/images/tripura-outfit.png",
    touristSpots: [{ name: "Ujjayanta Palace", image: "/images/ujjayanta-palace-header.png" }, { name: "Neermahal", image: "/images/neermahal.png" }],
  }
];